[package]
name = "wasmstandalone-tools"
authors = ["The Cretonne Project Developers"]
version = "0.0.0"
description = "Command-line interface for the wasmstandalone crate"
license = "MIT/Apache-2.0"
documentation = "https://cretonne.readthedocs.io/"
repository = "https://github.com/sunfishcode/wasmstandalone"
publish = false

[[bin]]
name = "wasmstandalone"
path = "src/main.rs"

[[bin]]
name = "wasm2obj"
path = "src/wasm2obj.rs"

[dependencies]
cretonne = { path = "/home/sunfish/rust/cretonne/lib/cretonne" }
cretonne-frontend = { path = "/home/sunfish/rust/cretonne/lib/frontend" }
cretonne-reader = { path = "/home/sunfish/rust/cretonne/lib/reader" }
cretonne-wasm = { path = "/home/sunfish/rust/cretonne/lib/wasm" }
cretonne-native = { path = "/home/sunfish/rust/cretonne/lib/native" }
wasmstandalone = { path = "lib/wasmstandalone" }
wasm2obj = { path = "lib/wasm2obj" }
wasmparser = "0.8.2"
wasmtext = { git = "https://github.com/yurydelendik/wasmtext" }
filecheck = "0.0.1"
docopt = "0.8.0"
serde = "1.0.8"
serde_derive = "1.0.8"
num_cpus = "1.5.1"
term = "0.4.6"
tempdir = "*"
faerie = { git = "https://github.com/m4b/faerie" }

[workspace]
