[package]
name = "wasmstandalone-tools"
authors = ["The Cretonne Project Developers"]
version = "0.0.0"
description = "Command-line interface for the wasmstandalone crate"
license = "Apache-2.0"
documentation = "https://cretonne.readthedocs.io/"
repository = "https://github.com/sunfishcode/wasmstandalone"
publish = false

[[bin]]
name = "wasmstandalone"
path = "src/main.rs"

[dependencies]
cretonne = { git = "https://github.com/stoklund/cretonne.git" }
cretonne-reader = { git = "https://github.com/stoklund/cretonne.git" }
cretonne-wasm = { git = "https://github.com/stoklund/cretonne.git" }
wasmstandalone = { path = "lib/wasmstandalone" }
wasmparser = "0.8.2"
wasmtext = { git = "https://github.com/yurydelendik/wasmtext" }
filecheck = "0.0.1"
docopt = "0.8.0"
serde = "1.0.8"
serde_derive = "1.0.8"
num_cpus = "1.5.1"
term = "0.4.6"
tempdir="*"

[workspace]
