[package]
name = "generate"
version = "0.1.0"
authors = ["Jakub Konka <jakub.konka@golem.network>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
witx = { path = "../WASI/tools/witx" }
quote = "1.0"
proc-macro2 = "1.0"
heck = "0.3"
